# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 00:19
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    def generate_usernames(apps, schema_editor):
        Rater = apps.get_model('recommender', 'Rater')
        raters = Rater.objects.all()
        for rater in raters:
            names = rater.name.split()
            user_name = names[1] + names[0][0] + str(rater.id)
            user = User.objects.create_user(first_name=names[0], last_name=names[1], username=user_name, password='default_pw')
            user.save()

    dependencies = [
        ('recommender', '0002_auto_20170323_0012'),
    ]

    operations = [
        migrations.RunPython(generate_usernames)
    ]
